plugins {
    id "com.android.application"
}

android {
    namespace = "ai.dirichlet.gamealgo.sample"
    compileSdk = 35

    defaultConfig {
        applicationId = "ai.dirichlet.gamealgo.sample"
        minSdk = 24
        targetSdk = 35
        versionCode = 1
        versionName = "1.0"
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }


    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }
}

dependencies {
    implementation(project(":"))
}
